---
- name: Download GPG key {{ gpg_name }}
  get_url:
    url: "{{ gpg_key }}"
    dest: "{{ repo_gpg_path }}/{{ repo_gpg_prefix }}{{ gpg_name }}"
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: cert_t
