---
- name: Download GPG key {{ repo_gpg_name }}
  get_url:
    url: "{{ repo_gpg_key }}"
    dest: "{{ repo_gpg_path }}/{{ repo_gpg_prefix }}{{ repo_gpg_name }}"
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: cert_t
