---
- name: Install GPG key
  include_tasks: "{{ gpg_key | search('^(ftp|https?)://') | ternary('download', 'copy') }}.yml"

- name: Import RPM GPG keys
  rpm_key: key=/etc/pki/rpm-gpg/{{ item }}
  with_items: "{{ rpm_gpg_keys }}"
  when: not ansible_check_mode

- name: Configure local repo
  template: >
    src=local.repo.j2
    dest=/etc/yum.repos.d/{{ localrepo_name }}.repo
