---
- name: Install GPG key {{ gpg_name }}
  include_tasks: "{{ gpg_key | search('^(ftp|https?)://') | ternary('download', 'copy') }}.yml"

- name: Import RPM GPG key {{ gpg_name }}
  rpm_key:
    key: "{{ repo_gpg_path }}/{{ repo_gpg_prefix }}{{ gpg_name }}"
  when: not ansible_check_mode
