---
- name: Install GPG key {{ repo_gpg_name }}
  include_tasks: |-
    {%  if repo_gpg_key is search('^(ftp|https?)://') -%}
    download.yml
    {%- else -%}
    copy.yml
    {%- endif %}

- name: Import RPM GPG key {{ repo_gpg_name }}
  rpm_key:
    key: "{{ repo_gpg_path }}/{{ repo_gpg_prefix }}{{ repo_gpg_name }}"
  when: not ansible_check_mode
